name: Controlador NODEJS

on:
  push:
    branches:
      -main
  pull_request:
    branches:
      -main
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Instalacion de dependecias 1
        run: npm install @testing-library/jest-dom
      - name: Instalacion de dependecias 2
        run: npm install @testing-library/react
      - name: Instalacion de dependecias 3
        run: npm install @testing-library/user-event
      - name: Instalacion de dependecias 4
        run: npm install bootstrap
      - name: Instalacion de dependecias 5
        run: npm install react
      - name: Instalacion de dependecias 6
        run: npm install react-dom
      - name: Instalacion de dependecias 7
        run: npm install react-scripts
      - name: Instalacion de dependecias 8
        run: npm install web-vitals
      - name: Inicio de dependecias 14
        run: npm install scripts
      
      
      
